# Generated by Django 2.0.5 on 2018-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(default='cse', max_length=120),
            preserve_default=False,
        ),
    ]
