# Generated by Django 2.0.5 on 2018-07-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_document_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(default='#', upload_to='images/'),
        ),
    ]
