# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_document_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('books', 'Books'), ('articles', 'Articles'), ('papers', 'Papers')], default='books', max_length=128),
            preserve_default=False,
        ),
    ]
